version: '3.3'
services:
    openlist:
        image: 'openlistteam/openlist:latest'
        container_name: openlist
        volumes:
            - './:/opt/openlist/data'
        ports:
            - '5244:5244'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        restart: unless-stopped
